/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.awt.HeadlessException;
import java.sql.*;
import java.text.SimpleDateFormat;
import javax.swing.ButtonGroup;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import pa_scholarhunt.Database;
import pa_scholarhunt.Beasiswa;

public final class DashboardAdmin extends javax.swing.JFrame {
    

    
    public DashboardAdmin() {
        initComponents();
        setupButtonGroup();
        Database.connect();
        initializeTable();
        loadTableData();
    }
    
    private void loadDataUser() {
    try (Connection conn = Database.connect()) {
        String query = "SELECT * FROM profil";
        try (var statement = conn.prepareStatement(query);
             ResultSet resultSet = statement.executeQuery()) {

            DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
            model.setRowCount(0); // Kosongkan tabel

            while (resultSet.next()) {
                Object[] row = {
                    resultSet.getString("Nama"),
                    resultSet.getString("NIM_NISN"),
                    resultSet.getString("Alamat"),
                    resultSet.getString("Status"),
                    resultSet.getString("No_Hp"),
                    resultSet.getString("Email"),
                    resultSet.getString("TTL")
                };
                model.addRow(row);
            }
        }
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Gagal memuat data user: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
} 
     

    private void setupButtonGroup() {
        ButtonGroup buttonGroup = new ButtonGroup();
        buttonGroup.add(jRadioButtonStatusBuka);
        buttonGroup.add(jRadioButtonStatusTutup);
    }
    
    private void initializeTable() {
    String[] columnNames = {"Nama", "NIM_NISN", "Alamat", "Status", "No_Hp", "Email", "TTL"};
    DefaultTableModel model = new DefaultTableModel(columnNames, 0);
    jTable2.setModel(model);
}

    void loadTableData() {
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("ID");
    model.addColumn("Nama Beasiswa");
    model.addColumn("Kategori");
    model.addColumn("Jenis");
    model.addColumn("Deadline");
    model.addColumn("Status");

    try (Connection conn = Database.connect()) {
        String query = "SELECT id_beasiswa, nama_beasiswa, kategori, jenis, deadline, status FROM beasiswa";
        Statement statement = conn.createStatement();
        ResultSet resultSet = statement.executeQuery(query);

        while (resultSet.next()) {
            model.addRow(new Object[]{
                resultSet.getInt("id_beasiswa"),
                resultSet.getString("nama_beasiswa"),
                resultSet.getString("kategori"),
                resultSet.getString("jenis"),
                resultSet.getDate("deadline"),
                resultSet.getString("status")
            });
        }
        jTable1.setModel(model);
        model.fireTableDataChanged();
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Gagal Memuat Data! " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }

}
    void clearTextFields() {
        jTextFieldIDBeasiswa.setText("");
        jTextFieldNamaBeasiswa.setText("");
        jComboBoxKategoriBeasiswa.setSelectedIndex(0);
        jTextFieldJenisBeasiswa.setText("");
        jTextFieldDeadline.setText("");
        jRadioButtonStatusBuka.setSelected(false);
        jRadioButtonStatusTutup.setSelected(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        bodypanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        ButtonAdmin = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel = new javax.swing.JLabel();
        ButtonUser = new javax.swing.JButton();
        ButtonLogout = new javax.swing.JButton();
        mainpanel = new javax.swing.JPanel();
        Datauser = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jButtontampilkanDataUser = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        Create = new javax.swing.JPanel();
        jLabelNamaBeasiswa = new javax.swing.JLabel();
        jTextFieldNamaBeasiswa = new javax.swing.JTextField();
        jLabelKategoriBeasiswa = new javax.swing.JLabel();
        jComboBoxKategoriBeasiswa = new javax.swing.JComboBox<>();
        jLabelJenisBeasiswa = new javax.swing.JLabel();
        jTextFieldJenisBeasiswa = new javax.swing.JTextField();
        jLabelDeadline = new javax.swing.JLabel();
        jTextFieldDeadline = new javax.swing.JTextField();
        jLabelStatus = new javax.swing.JLabel();
        jRadioButtonStatusBuka = new javax.swing.JRadioButton();
        jRadioButtonStatusTutup = new javax.swing.JRadioButton();
        jScrollPaneTabel = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonTambah = new javax.swing.JButton();
        jButtoneEdit = new javax.swing.JButton();
        jButtonHapus = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldIDBeasiswa = new javax.swing.JTextField();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        bodypanel.setBackground(new java.awt.Color(0, 51, 102));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        jPanel2.setPreferredSize(new java.awt.Dimension(152, 437));

        ButtonAdmin.setBackground(new java.awt.Color(0, 51, 102));
        ButtonAdmin.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ButtonAdmin.setForeground(new java.awt.Color(255, 255, 255));
        ButtonAdmin.setText("Dashboard Admin");
        ButtonAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAdminActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Rockwell Condensed", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 102));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Scholar");

        jLabel.setFont(new java.awt.Font("Rockwell Condensed", 1, 36)); // NOI18N
        jLabel.setForeground(new java.awt.Color(0, 51, 102));
        jLabel.setText("Hunt");

        ButtonUser.setBackground(new java.awt.Color(0, 51, 102));
        ButtonUser.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ButtonUser.setForeground(new java.awt.Color(255, 255, 255));
        ButtonUser.setText("Data User");
        ButtonUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonUserActionPerformed(evt);
            }
        });

        ButtonLogout.setBackground(new java.awt.Color(0, 51, 102));
        ButtonLogout.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ButtonLogout.setForeground(new java.awt.Color(255, 255, 255));
        ButtonLogout.setText("Keluar");
        ButtonLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel)
                        .addGap(0, 52, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ButtonLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonUser, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonAdmin))
                .addGap(19, 19, 19))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ButtonAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(ButtonUser, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(ButtonLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(199, 199, 199))
        );

        mainpanel.setBackground(new java.awt.Color(0, 51, 102));
        mainpanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        mainpanel.setLayout(new java.awt.CardLayout());

        Datauser.setBackground(new java.awt.Color(0, 51, 102));
        Datauser.setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 102));
        jLabel3.setText("Data User Terdaftar");

        jButtontampilkanDataUser.setBackground(new java.awt.Color(0, 51, 102));
        jButtontampilkanDataUser.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtontampilkanDataUser.setForeground(new java.awt.Color(255, 255, 255));
        jButtontampilkanDataUser.setText("Tampilkan Data User");
        jButtontampilkanDataUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtontampilkanDataUserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jButtontampilkanDataUser)
                .addGap(273, 273, 273)
                .addComponent(jLabel3)
                .addContainerGap(330, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtontampilkanDataUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        Datauser.add(jPanel1);
        jPanel1.setBounds(0, 0, 998, 64);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Nama", "NIM/NISN", "Alamat", "Status", "No. Hp", "Email", "TTL"
            }
        ));
        jTable2.setGridColor(new java.awt.Color(204, 204, 204));
        jTable2.setShowGrid(true);
        jScrollPane2.setViewportView(jTable2);

        Datauser.add(jScrollPane2);
        jScrollPane2.setBounds(14, 82, 978, 483);

        mainpanel.add(Datauser, "card3");

        Create.setBackground(new java.awt.Color(0, 51, 102));
        Create.setLayout(null);

        jLabelNamaBeasiswa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelNamaBeasiswa.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNamaBeasiswa.setText("Nama Beasiswa        :");
        Create.add(jLabelNamaBeasiswa);
        jLabelNamaBeasiswa.setBounds(40, 170, 150, 20);
        Create.add(jTextFieldNamaBeasiswa);
        jTextFieldNamaBeasiswa.setBounds(200, 170, 282, 30);

        jLabelKategoriBeasiswa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelKategoriBeasiswa.setForeground(new java.awt.Color(255, 255, 255));
        jLabelKategoriBeasiswa.setText("Kategori beasiswa    :");
        Create.add(jLabelKategoriBeasiswa);
        jLabelKategoriBeasiswa.setBounds(40, 220, 140, 20);

        jComboBoxKategoriBeasiswa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mahasiswa", "Siswa" }));
        Create.add(jComboBoxKategoriBeasiswa);
        jComboBoxKategoriBeasiswa.setBounds(200, 220, 280, 30);

        jLabelJenisBeasiswa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelJenisBeasiswa.setForeground(new java.awt.Color(255, 255, 255));
        jLabelJenisBeasiswa.setText("Jenis Beasiswa            :");
        Create.add(jLabelJenisBeasiswa);
        jLabelJenisBeasiswa.setBounds(530, 170, 162, 20);

        jTextFieldJenisBeasiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldJenisBeasiswaActionPerformed(evt);
            }
        });
        Create.add(jTextFieldJenisBeasiswa);
        jTextFieldJenisBeasiswa.setBounds(700, 170, 267, 30);

        jLabelDeadline.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelDeadline.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDeadline.setText("Deadline                      :");
        Create.add(jLabelDeadline);
        jLabelDeadline.setBounds(530, 220, 160, 20);

        jTextFieldDeadline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDeadlineActionPerformed(evt);
            }
        });
        Create.add(jTextFieldDeadline);
        jTextFieldDeadline.setBounds(700, 220, 267, 30);

        jLabelStatus.setBackground(new java.awt.Color(255, 255, 255));
        jLabelStatus.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelStatus.setForeground(new java.awt.Color(255, 255, 255));
        jLabelStatus.setText("Status                          :");
        Create.add(jLabelStatus);
        jLabelStatus.setBounds(530, 270, 160, 20);

        jRadioButtonStatusBuka.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jRadioButtonStatusBuka.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonStatusBuka.setText("Buka");
        jRadioButtonStatusBuka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonStatusBukaActionPerformed(evt);
            }
        });
        Create.add(jRadioButtonStatusBuka);
        jRadioButtonStatusBuka.setBounds(700, 270, 70, 21);

        jRadioButtonStatusTutup.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jRadioButtonStatusTutup.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonStatusTutup.setText("Tutup");
        jRadioButtonStatusTutup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonStatusTutupActionPerformed(evt);
            }
        });
        Create.add(jRadioButtonStatusTutup);
        jRadioButtonStatusTutup.setBounds(850, 270, 60, 21);

        jTable1.setBackground(new java.awt.Color(0, 51, 102));
        jTable1.setForeground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nama beasiswa", "Kategori", "Jenis", "Deadline", "Status"
            }
        ));
        jTable1.setGridColor(new java.awt.Color(255, 255, 255));
        jTable1.setShowGrid(true);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPaneTabel.setViewportView(jTable1);

        Create.add(jScrollPaneTabel);
        jScrollPaneTabel.setBounds(33, 319, 935, 208);

        jButtonTambah.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonTambah.setForeground(new java.awt.Color(0, 51, 102));
        jButtonTambah.setText("Tambah");
        jButtonTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTambahActionPerformed(evt);
            }
        });
        Create.add(jButtonTambah);
        jButtonTambah.setBounds(33, 539, 76, 23);

        jButtoneEdit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtoneEdit.setForeground(new java.awt.Color(0, 51, 102));
        jButtoneEdit.setText("Simpan Edit");
        jButtoneEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtoneEditActionPerformed(evt);
            }
        });
        Create.add(jButtoneEdit);
        jButtoneEdit.setBounds(131, 539, 97, 23);

        jButtonHapus.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonHapus.setForeground(new java.awt.Color(0, 51, 102));
        jButtonHapus.setText("Hapus");
        jButtonHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHapusActionPerformed(evt);
            }
        });
        Create.add(jButtonHapus);
        jButtonHapus.setBounds(253, 539, 72, 23);

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("DASHBOARD ADMIN");
        Create.add(jLabel4);
        jLabel4.setBounds(320, 50, 390, 70);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Blue Modern Business Webinar Zoom Virtual Background (1).png"))); // NOI18N
        Create.add(jLabel1);
        jLabel1.setBounds(0, 0, 1000, 590);

        jTextFieldIDBeasiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIDBeasiswaActionPerformed(evt);
            }
        });
        Create.add(jTextFieldIDBeasiswa);
        jTextFieldIDBeasiswa.setBounds(195, 171, 282, 22);

        mainpanel.add(Create, "card2");

        javax.swing.GroupLayout bodypanelLayout = new javax.swing.GroupLayout(bodypanel);
        bodypanel.setLayout(bodypanelLayout);
        bodypanelLayout.setHorizontalGroup(
            bodypanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodypanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainpanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1005, Short.MAX_VALUE)
                .addContainerGap())
        );
        bodypanelLayout.setVerticalGroup(
            bodypanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bodypanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bodypanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(mainpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bodypanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bodypanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldJenisBeasiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldJenisBeasiswaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldJenisBeasiswaActionPerformed

    private void jButtoneEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtoneEditActionPerformed
        // TODO add your handling code here:
        try {
        int row = jTable1.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, 
                "Silahkan pilih baris yang akan diubah!", 
                "Peringatan", 
                JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        int id = Integer.parseInt(jTable1.getValueAt(row, 0).toString());
        String namaBeasiswa = jTextFieldNamaBeasiswa.getText().trim();
        String kategori = jComboBoxKategoriBeasiswa.getSelectedItem().toString();
        String jenis = jTextFieldJenisBeasiswa.getText().trim();
        String deadline = jTextFieldDeadline.getText().trim();

        if (namaBeasiswa.isEmpty() || jenis.isEmpty() || deadline.isEmpty()) {
            JOptionPane.showMessageDialog(this, 
                "Semua kolom harus diisi!", 
                "Peringatan", 
                JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        String status = jRadioButtonStatusBuka.isSelected() ? "Buka" : 
                        jRadioButtonStatusTutup.isSelected() ? "Tutup" : "";

        if (status.isEmpty()) {
            JOptionPane.showMessageDialog(this, 
                "Silahkan pilih status beasiswa!", 
                "Peringatan", 
                JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        Beasiswa beasiswa = new Beasiswa(id, namaBeasiswa, kategori, jenis, deadline, status);
        boolean updated = beasiswa.updateBeasiswa();

        if (updated) {
            JOptionPane.showMessageDialog(this, 
                "Data beasiswa berhasil diubah!", 
                "Sukses", 
                JOptionPane.INFORMATION_MESSAGE
            );
        } else {
            JOptionPane.showMessageDialog(this, 
                "Gagal mengubah data beasiswa!", 
                "Error", 
                JOptionPane.ERROR_MESSAGE
            );
        }

        loadTableData();
        clearTextFields();

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, 
            "ID tidak valid!", 
            "Error", 
            JOptionPane.ERROR_MESSAGE
        );
    } catch (HeadlessException e) {
        JOptionPane.showMessageDialog(this, 
            "Terjadi kesalahan: " + e.getMessage(), 
            "Error", 
            JOptionPane.ERROR_MESSAGE
        );
    }
    }//GEN-LAST:event_jButtoneEditActionPerformed

    private void ButtonAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAdminActionPerformed
        // TODO add your handling code here:
        mainpanel.removeAll();
        mainpanel.repaint();
        mainpanel.revalidate();

        mainpanel.add(Create);
        mainpanel.repaint();
        mainpanel.revalidate();
    }//GEN-LAST:event_ButtonAdminActionPerformed

    private void ButtonUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonUserActionPerformed
        mainpanel.removeAll();
        mainpanel.repaint();
        mainpanel.revalidate();

        mainpanel.add(Datauser);
        mainpanel.repaint();
        mainpanel.revalidate();        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonUserActionPerformed

    private void jButtonHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHapusActionPerformed
        // TODO add your handling code here:
        try {
        int row = jTable1.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, 
                "Silahkan pilih baris yang akan dihapus!", 
                "Peringatan", 
                JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        int id = Integer.parseInt(jTable1.getValueAt(row, 0).toString());
        Beasiswa beasiswa = new Beasiswa(id, "", "", "", "", "");
        beasiswa.deleteBeasiswa();

        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.removeRow(row);

        JOptionPane.showMessageDialog(this, 
            "Beasiswa berhasil dihapus!", 
            "Sukses", 
            JOptionPane.INFORMATION_MESSAGE
        );
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, 
            "ID tidak valid!", 
            "Error", 
            JOptionPane.ERROR_MESSAGE
        );
    } catch (HeadlessException e) {
        JOptionPane.showMessageDialog(this, 
            "Terjadi kesalahan: " + e.getMessage(), 
            "Error", 
            JOptionPane.ERROR_MESSAGE
        );
    }

    }//GEN-LAST:event_jButtonHapusActionPerformed

    private void jButtonTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTambahActionPerformed
        try {
        String namaBeasiswa = jTextFieldNamaBeasiswa.getText().trim();
        String kategoriBeasiswa = jComboBoxKategoriBeasiswa.getSelectedItem().toString();
        String jenisBeasiswa = jTextFieldJenisBeasiswa.getText().trim();
        String deadline = jTextFieldDeadline.getText().trim();
        String status = jRadioButtonStatusBuka.isSelected() ? "Buka" : 
                        jRadioButtonStatusTutup.isSelected() ? "Tutup" : "";

        if (namaBeasiswa.isEmpty() || jenisBeasiswa.isEmpty() || deadline.isEmpty() || status.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Semua kolom harus diisi!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String checkQuery = "SELECT COUNT(*) FROM beasiswa WHERE nama_beasiswa = ?";
        try (Connection conn = Database.connect();
             PreparedStatement checkStatement = conn.prepareStatement(checkQuery)) {

            checkStatement.setString(1, namaBeasiswa);
            ResultSet resultSet = checkStatement.executeQuery();
            resultSet.next();
            int count = resultSet.getInt(1);

            if (count > 0) {
                JOptionPane.showMessageDialog(this, "Nama beasiswa sudah ada di database!", "Peringatan", JOptionPane.WARNING_MESSAGE);
                return;
            }

            String insertQuery = "INSERT INTO beasiswa (nama_beasiswa, kategori, jenis, deadline, status) VALUES (?, ?, ?, ?, ?)";
            try (PreparedStatement insertStatement = conn.prepareStatement(insertQuery, Statement.RETURN_GENERATED_KEYS)) {
                insertStatement.setString(1, namaBeasiswa);
                insertStatement.setString(2, kategoriBeasiswa);
                insertStatement.setString(3, jenisBeasiswa);
                insertStatement.setString(4, deadline);
                insertStatement.setString(5, status);

                int rowsInserted = insertStatement.executeUpdate();
                if (rowsInserted > 0) {
                    try (ResultSet generatedKeys = insertStatement.getGeneratedKeys()) {
                        if (generatedKeys.next()) {
                            int generatedID = generatedKeys.getInt(1);
                            System.out.println("ID Beasiswa yang baru dibuat: " + generatedID);
                            jTextFieldIDBeasiswa.setText(String.valueOf(generatedID));
                        }
                    }
                    JOptionPane.showMessageDialog(this, "Beasiswa berhasil ditambahkan!", "Sukses", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(this, "Gagal menyimpan beasiswa.", "Error", JOptionPane.ERROR_MESSAGE);
                }

            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }

        loadTableData();
        clearTextFields();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }

    }//GEN-LAST:event_jButtonTambahActionPerformed

    private void jRadioButtonStatusTutupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonStatusTutupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonStatusTutupActionPerformed

    private void jRadioButtonStatusBukaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonStatusBukaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonStatusBukaActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
         int row = jTable1.getSelectedRow();  // Mendapatkan baris yang dipilih
        if (row != -1) {
            // Mengambil data dari baris yang dipilih
            int id = (int) jTable1.getValueAt(row, 0);  // ID Beasiswa
            String nama = (String) jTable1.getValueAt(row, 1);  // Nama Beasiswa
            String kategori = (String) jTable1.getValueAt(row, 2);  // Kategori
            String jenis = (String) jTable1.getValueAt(row, 3);  // Jenis Beasiswa
            Date deadline = (Date) jTable1.getValueAt(row, 4);  // Deadline
            String status = (String) jTable1.getValueAt(row, 5);  // Status

            // Memasukkan data ke dalam form input
            jTextFieldIDBeasiswa.setText(String.valueOf(id));
            jTextFieldNamaBeasiswa.setText(nama);
            jComboBoxKategoriBeasiswa.setSelectedItem(kategori);
            jTextFieldJenisBeasiswa.setText(jenis);
            jTextFieldDeadline.setText(new SimpleDateFormat("yyyy-MM-dd").format(deadline));

            // Menentukan status berdasarkan data yang dipilih
            if (status.equals("Buka")) {
                jRadioButtonStatusBuka.setSelected(true);
            } else {
                jRadioButtonStatusTutup.setSelected(true);
            }
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void ButtonLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonLogoutActionPerformed
        // TODO add your handling code here:
        int confirm = javax.swing.JOptionPane.showConfirmDialog(
        this, 
        "Apakah Anda yakin ingin logout?", 
        "Konfirmasi Logout", 
        javax.swing.JOptionPane.YES_NO_OPTION
    );

    
    if (confirm == javax.swing.JOptionPane.YES_OPTION) {
       
        this.dispose();
        
       
        Login login = new Login(); 
        login.setVisible(true);
    }
    }//GEN-LAST:event_ButtonLogoutActionPerformed

    private void jTextFieldIDBeasiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIDBeasiswaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIDBeasiswaActionPerformed

    private void jButtontampilkanDataUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtontampilkanDataUserActionPerformed
    loadDataUser();// TODO add your handling code here:
    }//GEN-LAST:event_jButtontampilkanDataUserActionPerformed

    private void jTextFieldDeadlineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDeadlineActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDeadlineActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashboardAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonAdmin;
    private javax.swing.JButton ButtonLogout;
    private javax.swing.JButton ButtonUser;
    private javax.swing.JPanel Create;
    private javax.swing.JPanel Datauser;
    private javax.swing.JPanel bodypanel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButtonHapus;
    private javax.swing.JButton jButtonTambah;
    private javax.swing.JButton jButtoneEdit;
    private javax.swing.JButton jButtontampilkanDataUser;
    private javax.swing.JComboBox<String> jComboBoxKategoriBeasiswa;
    private javax.swing.JLabel jLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelDeadline;
    private javax.swing.JLabel jLabelJenisBeasiswa;
    private javax.swing.JLabel jLabelKategoriBeasiswa;
    private javax.swing.JLabel jLabelNamaBeasiswa;
    private javax.swing.JLabel jLabelStatus;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButtonStatusBuka;
    private javax.swing.JRadioButton jRadioButtonStatusTutup;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPaneTabel;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextFieldDeadline;
    private javax.swing.JTextField jTextFieldIDBeasiswa;
    private javax.swing.JTextField jTextFieldJenisBeasiswa;
    private javax.swing.JTextField jTextFieldNamaBeasiswa;
    private javax.swing.JPanel mainpanel;
    // End of variables declaration//GEN-END:variables
}
